# Generated by Django 5.0.3 on 2024-06-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='first_name',
            field=models.CharField(default='', help_text='Por favor, introduzca su nombre.', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='coach',
            name='last_name',
            field=models.CharField(default='', help_text='Por favor, introduzca sus apellidos.', max_length=100, verbose_name='Apellidos'),
        ),
    ]
