# Generated by Django 5.0.3 on 2024-06-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_coach_first_name_coach_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'Entrenador', 'verbose_name_plural': 'Entrenadores'},
        ),
    ]
