# Generated by Django 5.0.3 on 2024-06-03 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coach', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(help_text='Por favor, introduzca su fecha de nacimiento.', verbose_name='Fecha de nacimiento')),
                ('city', models.CharField(help_text='Por favor, introduzca su ciudad de residencia.', max_length=100, verbose_name='Ciudad')),
                ('occupation', models.CharField(help_text='Por favor, introduzca su ocupación.', max_length=100, verbose_name='Ocupación')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.coach')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
