# Generated by Django 5.0.3 on 2024-06-05 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('coach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='coach',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='coach.coach'),
        ),
    ]
