# Generated by Django 5.0.3 on 2024-06-05 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_coach'),
        ('coach', '0002_coach_first_name_coach_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='', help_text='Por favor, introduzca su nombre.', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', help_text='Por favor, introduzca sus apellidos.', max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='client',
            name='coach',
            field=models.ForeignKey(help_text='Entrenador asignado al cliente.', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='coach.coach', verbose_name='Entrenador'),
        ),
        migrations.AlterField(
            model_name='client',
            name='occupation',
            field=models.CharField(blank=True, help_text='Por favor, introduzca su ocupación.', max_length=100, null=True, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(help_text='Usuario registrado asociado al cliente.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
