# Generated by Django 5.0.3 on 2024-06-05 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_alter_client_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePersonalTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Descripción del entrenamiento.', null=True, verbose_name='Descripción')),
                ('duration', models.DurationField(blank=True, help_text='Duración del entrenamiento.', null=True, verbose_name='Duración')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='client.client')),
            ],
        ),
        migrations.CreateModel(
            name='NamedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre del grupo.', max_length=50, null=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineTraining',
            fields=[
                ('basepersonaltraining_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='training.basepersonaltraining')),
                ('year', models.PositiveSmallIntegerField(help_text='Año del entrenamiento.', verbose_name='Año')),
                ('month', models.PositiveSmallIntegerField(help_text='Mes del entrenamiento.', verbose_name='Mes')),
                ('week', models.PositiveSmallIntegerField(blank=True, help_text='Semana del mes.', null=True, verbose_name='Semana')),
            ],
            bases=('training.basepersonaltraining',),
        ),
        migrations.CreateModel(
            name='GroupTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha del entrenamiento.', verbose_name='Fecha')),
                ('hour', models.PositiveSmallIntegerField(help_text='Hora del entrenamiento.', verbose_name='Hora')),
                ('named_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_trainings', to='training.namedgroup')),
            ],
        ),
        migrations.CreateModel(
            name='PersonGroupTraining',
            fields=[
                ('basepersonaltraining_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='training.basepersonaltraining')),
                ('group_training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_trainings', to='training.grouptraining')),
            ],
            bases=('training.basepersonaltraining',),
        ),
    ]
