# Generated by Django 5.0.3 on 2024-06-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_coach'),
        ('training', '0002_namedgroup_components_alter_onlinetraining_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptraining',
            name='components',
            field=models.ManyToManyField(related_name='group_trainings', to='client.client'),
        ),
    ]
