# Generated by Django 5.0.3 on 2024-06-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_coach'),
        ('training', '0003_grouptraining_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptraining',
            name='components',
            field=models.ManyToManyField(blank=True, help_text='Si un cliente está en un grupo nombrado, no es necesario añadirlo de nuevo.', related_name='group_trainings', to='client.client', verbose_name='Clientes extra'),
        ),
        migrations.AlterField(
            model_name='namedgroup',
            name='components',
            field=models.ManyToManyField(help_text='Clientes que pertenecen al grupo.', related_name='named_groups', to='client.client', verbose_name='Clientes'),
        ),
    ]
