# Generated by Django 5.0.3 on 2024-06-05 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_first_name_client_last_name_and_more'),
        ('training', '0004_alter_grouptraining_components_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptraining',
            name='components',
            field=models.ManyToManyField(blank=True, help_text='Si se ha seleccionado un grupo nombrado, no es obligatorio.', related_name='group_trainings', to='client.client', verbose_name='Clientes extra'),
        ),
        migrations.AlterField(
            model_name='grouptraining',
            name='named_group',
            field=models.ForeignKey(blank=True, help_text='Los clientes de este grupo se añadirán automáticamente.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_trainings', to='training.namedgroup', verbose_name='Grupo nombrado'),
        ),
    ]
