# Generated by Django 5.0.3 on 2024-06-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_method_name_alter_musculargroup_name_and_more'),
        ('training', '0005_alter_grouptraining_components_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinetraining',
            name='exercises_set',
            field=models.ManyToManyField(blank=True, help_text='Ejercicios del entrenamiento.', related_name='online_trainings', to='exercise.exerciseset', verbose_name='Ejercicios'),
        ),
    ]
