# Generated by Django 5.0.3 on 2024-06-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_onlinetraining_exercises_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinetraining',
            name='exercises_set',
        ),
    ]
