# Generated by Django 5.0.3 on 2024-06-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_remove_onlinetraining_exercises_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basepersonaltraining',
            name='duration',
            field=models.CharField(blank=True, help_text='Duración del entrenamiento.', max_length=50, null=True, verbose_name='Duración'),
        ),
    ]
