# Generated by Django 5.0.3 on 2024-06-07 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_coach_first_name_coach_last_name'),
        ('training', '0008_alter_basepersonaltraining_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptraining',
            name='group_coach',
            field=models.ForeignKey(default=1, help_text='Entrenador del grupo.', on_delete=django.db.models.deletion.CASCADE, related_name='named_groups', to='coach.coach', verbose_name='Entrenador'),
        ),
    ]
