# Generated by Django 5.0.3 on 2024-06-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_grouptraining_group_coach'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouptraining',
            options={'verbose_name': 'Entrenamiento en grupo', 'verbose_name_plural': 'Entrenamientos en grupo'},
        ),
        migrations.AlterModelOptions(
            name='namedgroup',
            options={'verbose_name': 'Grupo nombrado', 'verbose_name_plural': 'Grupos nombrados'},
        ),
        migrations.AlterModelOptions(
            name='onlinetraining',
            options={'verbose_name': 'Entrenamiento online', 'verbose_name_plural': 'Entrenamientos online'},
        ),
    ]
