# Generated by Django 5.0.3 on 2024-06-05 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del ejercicio.', max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción del ejercicio.', null=True, verbose_name='Descripción')),
                ('video', models.URLField(blank=True, help_text='URL del vídeo.', null=True, verbose_name='Vídeo')),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del método.', max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, help_text='Descripción del método.', null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='MuscularGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del grupo muscular.', max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del objetivo.', max_length=100, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_per_repetitions', models.CharField(blank=True, help_text='Descripción de las series y repeticiones o tiempo.', max_length=50, null=True, verbose_name='Series X Repeticiones')),
                ('rest', models.DurationField(blank=True, help_text='Tiempo de descanso entre series.', null=True, verbose_name='Descanso')),
                ('observations', models.TextField(blank=True, help_text='Observaciones del ejercicio.', null=True, verbose_name='Observaciones')),
                ('exercise', models.ForeignKey(help_text='Ejercicio al que pertenece la serie.', on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='exercise.exercise', verbose_name='Ejercicio')),
                ('execution_method', models.ForeignKey(blank=True, help_text='Método de ejecución del ejercicio.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='exercise.method', verbose_name='Método de ejecución')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscular_group',
            field=models.ForeignKey(blank=True, help_text='Grupo muscular al que pertenece el ejercicio.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercise.musculargroup', verbose_name='Grupo muscular'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='objective',
            field=models.ForeignKey(blank=True, help_text='Objetivo del ejercicio.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercise.objective', verbose_name='Objetivo'),
        ),
    ]
