# Generated by Django 5.0.3 on 2024-06-05 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_method_name_alter_musculargroup_name_and_more'),
        ('training', '0007_remove_onlinetraining_exercises_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineExerciseSet',
            fields=[
                ('exerciseset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exercise.exerciseset')),
                ('online_training', models.ForeignKey(help_text='Entrenamiento online al que pertenece la serie.', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.onlinetraining', verbose_name='Entrenamiento online')),
            ],
            bases=('exercise.exerciseset',),
        ),
    ]
