# Generated by Django 5.0.3 on 2024-06-05 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_onlineexerciseset'),
        ('training', '0008_alter_basepersonaltraining_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='rest',
            field=models.CharField(blank=True, help_text='Tiempo de descanso entre series.', max_length=50, null=True, verbose_name='Descanso'),
        ),
        migrations.CreateModel(
            name='GroupExerciseSet',
            fields=[
                ('exerciseset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exercise.exerciseset')),
                ('group_training', models.ForeignKey(help_text='Entrenamiento en grupo al que pertenece la serie.', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.grouptraining', verbose_name='Entrenamiento en grupo')),
            ],
            bases=('exercise.exerciseset',),
        ),
    ]
