# Generated by Django 5.0.3 on 2024-06-05 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_first_name_client_last_name_and_more'),
        ('exercise', '0004_alter_exerciseset_rest_groupexerciseset'),
        ('training', '0008_alter_basepersonaltraining_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupexerciseset',
            name='group_training',
        ),
        migrations.CreateModel(
            name='GroupSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(help_text='Cliente del grupo al que pertenece la serie.', on_delete=django.db.models.deletion.CASCADE, related_name='group_sets', to='client.client', verbose_name='Cliente')),
                ('group_training', models.ForeignKey(help_text='Entrenamiento en grupo al que pertenece la serie.', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.grouptraining', verbose_name='Entrenamiento en grupo')),
            ],
        ),
        migrations.AddField(
            model_name='groupexerciseset',
            name='group_set',
            field=models.ForeignKey(default=1, help_text='Grupo de series al que pertenece la serie.', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercise.groupset', verbose_name='Grupo de series'),
        ),
    ]
