# Generated by Django 5.0.3 on 2024-06-05 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_first_name_client_last_name_and_more'),
        ('exercise', '0005_remove_groupexerciseset_group_training_groupset_and_more'),
        ('training', '0008_alter_basepersonaltraining_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupexerciseset',
            name='group_set',
        ),
        migrations.AddField(
            model_name='groupexerciseset',
            name='client',
            field=models.ForeignKey(help_text='Cliente del grupo al que pertenece la serie.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_sets', to='client.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='groupexerciseset',
            name='group_training',
            field=models.ForeignKey(help_text='Entrenamiento en grupo al que pertenece la serie.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='training.grouptraining', verbose_name='Entrenamiento en grupo'),
        ),
        migrations.DeleteModel(
            name='GroupSet',
        ),
    ]
