# Generated by Django 5.0.3 on 2024-06-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_remove_groupexerciseset_group_set_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Ejercicio', 'verbose_name_plural': 'Ejercicios'},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'verbose_name': 'Método de ejecución', 'verbose_name_plural': 'Métodos de ejecución'},
        ),
        migrations.AlterModelOptions(
            name='musculargroup',
            options={'verbose_name': 'Grupo muscular', 'verbose_name_plural': 'Grupos musculares'},
        ),
        migrations.AlterModelOptions(
            name='objective',
            options={'verbose_name': 'Objetivo', 'verbose_name_plural': 'Objetivos'},
        ),
    ]
