# Generated by Django 5.0.3 on 2024-06-06 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateField(default=datetime.date.today, editable=False, help_text='Fecha del informe.', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='report',
            name='diet_changes',
            field=models.TextField(blank=True, help_text='¿Te gustaría añadir o eliminar algún alimento de tu dieta? ¿Por qué?', null=True, verbose_name='Cambios en la dieta'),
        ),
        migrations.AlterField(
            model_name='report',
            name='other_observations',
            field=models.TextField(blank=True, help_text='¿Hay algo más que te gustaría compartir?', null=True, verbose_name='Otras observaciones'),
        ),
        migrations.AlterField(
            model_name='report',
            name='training_observations',
            field=models.TextField(blank=True, help_text='¿Qué ejercicios te han producido mejor sensación?¿Cuáles te han resultado más difíciles?', null=True, verbose_name='Observaciones del entrenamiento'),
        ),
    ]
