# Generated by Django 5.0.3 on 2024-06-06 17:31

import apps.reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_date_alter_report_diet_changes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='front_picture',
            field=models.ImageField(help_text='Foto frontal del cuerpo actualmente.', upload_to=apps.reports.models.get_upload_to, verbose_name='Foto frontal'),
        ),
        migrations.AlterField(
            model_name='report',
            name='left_side_picture',
            field=models.ImageField(help_text='Foto lateral izquierda del cuerpo actualmente.', upload_to=apps.reports.models.get_upload_to, verbose_name='Foto lateral izquierda'),
        ),
        migrations.AlterField(
            model_name='report',
            name='right_side_picture',
            field=models.ImageField(help_text='Foto lateral derecha del cuerpo actualmente.', upload_to=apps.reports.models.get_upload_to, verbose_name='Foto lateral derecha'),
        ),
    ]
